DROP DATABASE IF EXISTS daytrading;
DROP USER IF EXISTS seng468;
CREATE USER seng468 WITH ENCRYPTED PASSWORD 'seng468';
CREATE DATABASE daytrading OWNER seng468;
GRANT ALL PRIVILEGES ON DATABASE daytrading TO seng468;